// <auto-generated />
using System;
using ComunicaMais.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ComunicaMais.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComunicaMais.API.Models.Device", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<DateTime>("LastSeen")
                    .HasColumnType("TIMESTAMP(7)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("NVARCHAR2(50)");

                b.HasKey("Id");

                b.ToTable("Devices");
            });

            modelBuilder.Entity("ComunicaMais.API.Models.Message", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)");

                b.Property<int>("DeviceId")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("Sender")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.HasKey("Id");

                b.HasIndex("DeviceId");

                b.ToTable("Messages");
            });

            modelBuilder.Entity("ComunicaMais.API.Models.Message", b =>
            {
                b.HasOne("ComunicaMais.API.Models.Device", "Device")
                    .WithMany("Messages")
                    .HasForeignKey("DeviceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Device");
            });

            modelBuilder.Entity("ComunicaMais.API.Models.Device", b =>
            {
                b.Navigation("Messages");
            });
#pragma warning restore 612, 618
        }
    }
}
